apiVersion: apps/v1
kind: Deployment
metadata:
  name: db
spec:
  replicas: 1
  selector:
    matchLabels:
      service: db
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        service: db
    spec:
      containers:
        - env:
            - name: DATABASE_PASSWORD
              valueFrom:
                configMapKeyRef:
                  key: DATABASE_PASSWORD
                  name: env-secrets
            - name: DATABASE_PORT
              valueFrom:
                configMapKeyRef:
                  key: DATABASE_PORT
                  name: env-secrets
            - name: DATABASE_URL
              valueFrom:
                configMapKeyRef:
                  key: DATABASE_URL
                  name: env-secrets
            - name: DATABASE_USER
              valueFrom:
                configMapKeyRef:
                  key: DATABASE_USER
                  name: env-secrets
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  key: POSTGRES_DB
                  name: env-secrets
            - name: POSTGRES_HOST_AUTH_METHOD
              valueFrom:
                configMapKeyRef:
                  key: POSTGRES_HOST_AUTH_METHOD
                  name: env-secrets
            - name: RACK_ENV
              valueFrom:
                configMapKeyRef:
                  key: RACK_ENV
                  name: env-secrets
            - name: RAILS_ENV
              valueFrom:
                configMapKeyRef:
                  key: RAILS_ENV
                  name: env-secrets
            - name: RAILS_LOG_TO_STDOUT
              valueFrom:
                configMapKeyRef:
                  key: RAILS_LOG_TO_STDOUT
                  name: env-secrets
            - name: RAILS_SERVE_STATIC_FILES
              valueFrom:
                configMapKeyRef:
                  key: RAILS_SERVE_STATIC_FILES
                  name: env-secrets
            - name: SECRET_KEY_BASE
              valueFrom:
                configMapKeyRef:
                  key: SECRET_KEY_BASE
                  name: env-secrets
          image: postgres:15.1-alpine
          name: db
          ports:
            - containerPort: 5432
          resources: {}
          volumeMounts:
            - mountPath: /usr/local/pgsql/data
              name: db-data
      restartPolicy: Always
      volumes:
        - name: db-data
          persistentVolumeClaim:
            claimName: db-data